GET  http://localhost:5000/userorder
###

GET  http://localhost:5000/games
###

GET  http://localhost:5000/gamepubgm
###

GET  http://localhost:5000/userorder/3
###

POST http://localhost:5000/userorder/
Content-Type: application/json

{
    "Email" : "sandikroon23@gmail.com",
    "Amount" : "50 UC"
}

###
PATCH  http://localhost:5000/userorder/2
Content-Type: application/json

{
    "Email" : "sandi.ganteng@live.com",
    "Amount" : "700 Diamonds"
}

###

DELETE   http://localhost:5000/userorder/3

