GET  http://localhost:5000/
###

GET  http://localhost:5000/userorder
###

GET  https://rich-teal-turkey-veil.cyclic.app/userorder

###
GET  https://rich-teal-turkey-veil.cyclic.app/games

###

GET  http://localhost:5000/gamepubgm
###

GET  http://localhost:5000/userorder/3
###

POST http://rich-teal-turkey-veil.cyclic.app/userorder
Content-Type: application/json

{
    "Email" : "sandikroon23@gmail.com",
    "GameID":"456456",
    "ZoneID" :"",
    "Amount" : "Digital Ocean TEST",
    "Game" : "PUBGM"
}
###

POST https://rich-teal-turkey-veil.cyclic.app/userorder
Content-Type: application/json

{
    "Email" : "sandikroon23@gmail.com",
    "GameID":"'829978013'",
    "ZoneID" :"",
    "Amount" : "Digital Ocean DB TEST",
    "Game" : "PUBGM"
}

###
PATCH  http://localhost:5000/userorder/2
Content-Type: application/json

{
    "Email" : "sandi.ganteng@live.com",
    "Amount" : "700 Diamonds"
}

###

DELETE   http://localhost:5000/userorder/3

